'use strict';

const { app, BrowserWindow, globalShortcut, ipcMain, screen, Menu, Tray, nativeImage, shell } = require('electron');
const path = require('node:path');
const Store = require('electron-store');
const { CURRENT_SCHEMA_VERSION, isValidUrl, normalizeCard, normalizeCardGraph, normalizeConnections, migrateState } = require('./card-schema.cjs');
const { MAX_PROFILES, makeProfileId, uniqueProfileName, normalizeProfileList } = require('./profile-schema.cjs');

let wallpaperApi = null;
if (process.platform === 'win32') {
  try { wallpaperApi = require('./win32-wallpaper.cjs'); }
  catch (err) { console.error('[DexPad] Failed to load native wallpaper module:', err); }
}
if (!app.requestSingleInstanceLock()) { app.quit(); process.exit(0); }

const store = new Store({ name:'dexpad', defaults:{ schemaVersion:CURRENT_SCHEMA_VERSION, startup:false, wallpaperMode:false, profiles:[], activeProfileId:null } });
const legacyState = migrateState(store.store);
let profiles = normalizeProfileList(store.get('profiles'), normalizeCardGraph, normalizeConnections, legacyState);
let activeProfileId = typeof store.get('activeProfileId') === 'string' && profiles.some(p=>p.id===store.get('activeProfileId')) ? store.get('activeProfileId') : profiles[0].id;
store.set('profiles', profiles); store.set('activeProfileId', activeProfileId); store.set('schemaVersion', CURRENT_SCHEMA_VERSION);

let workspaceWin=null, desktopWin=null, settingsWin=null, tray=null, quitting=false;
const RENDERER=path.join(__dirname,'../renderer'), WORKSPACE_HTML=path.join(RENDERER,'workspace.html'), PRELOAD=path.join(RENDERER,'../preload/preload.cjs');
function getActiveProfile(){return profiles.find(p=>p.id===activeProfileId)||profiles[0];}
function getControlDisplay(){try{const pt=screen.getCursorScreenPoint();return screen.getDisplayNearestPoint(pt)||screen.getPrimaryDisplay();}catch(_){return screen.getPrimaryDisplay();}}
function getWallpaperDisplay(){return screen.getPrimaryDisplay();}
function controlBounds(d=null){const display=d||getControlDisplay(),wa=display.workArea,w=Math.min(1180,Math.max(900,Math.round(wa.width*.78))),h=Math.min(860,Math.max(620,Math.round(wa.height*.82)));return{x:Math.round(wa.x+(wa.width-w)/2),y:Math.round(wa.y+(wa.height-h)/2),width:w,height:h};}
function wallpaperPanelBounds(d=null){const display=d||getWallpaperDisplay();const w=Math.min(1180,Math.round(display.bounds.width*.78)),h=Math.min(860,Math.round(display.bounds.height*.82));return{x:display.bounds.x+Math.round((display.bounds.width-w)/2),y:display.bounds.y+Math.round((display.bounds.height-h)/2),width:w,height:h};}
function wallpaperNativePosition(_display,dipBounds){const p=screen.dipToScreenPoint({x:dipBounds.x,y:dipBounds.y});return{x:Math.round(p.x),y:Math.round(p.y),width:dipBounds.width,height:dipBounds.height};}
function getCards(){return normalizeCardGraph(getActiveProfile()?.cards||[]);} function getConnections(){return normalizeConnections(getActiveProfile()?.connections,getCards());}
function profileSummary(){return profiles.map(p=>({id:p.id,name:p.name}));}
function currentState(){return{schemaVersion:CURRENT_SCHEMA_VERSION,startup:Boolean(store.get('startup')),wallpaperMode:Boolean(store.get('wallpaperMode')),profiles:profileSummary(),activeProfileId,cards:getCards(),connections:getConnections()};}
function persistProfiles(){store.set('profiles',profiles);store.set('activeProfileId',activeProfileId);}
function publishState(excludeSender=null){if(quitting)return;const state=currentState();for(const win of [workspaceWin,desktopWin]){if(!win||win.isDestroyed()||(excludeSender&&win.webContents===excludeSender))continue;try{win.webContents.send('dexpad:state-updated',state);}catch(err){console.warn('[DexPad] state publish failed:',err.message);}}}
let saveQueue=Promise.resolve();
function saveWorkspace(rawCards,rawConnections,excludeSender=null,targetProfileId=null){let cardsInput=rawCards,connectionsInput=rawConnections,bound=targetProfileId;if(rawCards&&!Array.isArray(rawCards)&&typeof rawCards==='object'&&Array.isArray(rawCards.cards)){cardsInput=rawCards.cards;connectionsInput=rawCards.connections;bound=rawCards.profileId||bound;}const profileId=bound||activeProfileId;const op=saveQueue.then(()=>{const c=normalizeCardGraph(Array.isArray(cardsInput)?cardsInput.map((x,i)=>normalizeCard(x,i)).filter(Boolean):[]),e=normalizeConnections(connectionsInput,c),p=profiles.find(x=>x.id===profileId);if(!p)return{cards:c,connections:e};p.cards=c;p.connections=e;persistProfiles();publishState(excludeSender);return{cards:c,connections:e};});saveQueue=op.catch(err=>console.error('[DexPad] saveWorkspace:',err));return op;}
function saveWorkspaceSync(payload){const profileId=payload?.profileId||activeProfileId;const op=saveQueue.then(()=>{const p=profiles.find(x=>x.id===profileId);if(!p)return;const c=normalizeCardGraph(Array.isArray(payload?.cards)?payload.cards.map((x,i)=>normalizeCard(x,i)).filter(Boolean):[]),e=normalizeConnections(payload?.connections,c);p.cards=c;p.connections=e;persistProfiles();});saveQueue=op.catch(err=>console.error('[DexPad] sync save:',err));return op;}
function applyStartup(enabled){store.set('startup',enabled);app.setLoginItemSettings({openAtLogin:enabled,args:['--hidden']});}
function switchProfile(id){if(!profiles.some(p=>p.id===id))throw new Error('Profile not found.');const op=saveQueue.then(()=>{activeProfileId=id;persistProfiles();publishState();return currentState();});saveQueue=op.catch(err=>console.error('[DexPad] switchProfile:',err));return op;}
function createProfile(name){if(profiles.length>=MAX_PROFILES)throw new Error(`Maximum profile limit (${MAX_PROFILES}) reached.`);const p={id:makeProfileId(new Set(profiles.map(x=>x.id))),name:uniqueProfileName(name,profiles.map(x=>x.name),profiles.length+1),cards:[],connections:[]};const op=saveQueue.then(()=>{profiles.push(p);activeProfileId=p.id;persistProfiles();publishState();return currentState();});saveQueue=op.catch(err=>console.error('[DexPad] createProfile:',err));return op;}
function renameProfile(id,name){const p=profiles.find(x=>x.id===id);if(!p)throw new Error('Profile not found.');const clean=String(name||'').trim();if(!clean)throw new Error('Profile name cannot be empty.');p.name=uniqueProfileName(clean,profiles.filter(x=>x.id!==id).map(x=>x.name));persistProfiles();publishState();return currentState();}
function showControlWindow(){if(workspaceWin&&!workspaceWin.isDestroyed()){workspaceWin.show();workspaceWin.focus();return workspaceWin;}return createControlWindow();}
function createControlWindow(){workspaceWin=new BrowserWindow({...controlBounds(),show:false,frame:true,resizable:true,movable:true,minimizable:true,maximizable:true,focusable:true,skipTaskbar:false,title:'DexPad',backgroundColor:'#090b0e',webPreferences:{contextIsolation:true,sandbox:true,preload:PRELOAD}});workspaceWin.setMenuBarVisibility(false);workspaceWin.loadFile(WORKSPACE_HTML,{search:'mode=control'}).catch(e=>console.error('[DexPad] load control:',e.message));workspaceWin.once('ready-to-show',()=>{workspaceWin.show();workspaceWin.focus();});workspaceWin.on('closed',()=>{workspaceWin=null;});return workspaceWin;}
const ATTACH_MAX=6,ATTACH_DELAY=1000;let attachTries=0,attachBusy=false,attachTimer=null,explorerWatchTimer=null,isWallpaperAttached=false;
function attachWallpaper(){if(!desktopWin||desktopWin.isDestroyed()||!wallpaperApi||attachBusy)return;if(attachTimer){clearTimeout(attachTimer);attachTimer=null;}attachBusy=true;doAttach();}
function doAttach(){if(!desktopWin||desktopWin.isDestroyed()){attachBusy=false;return;}try{const d=getWallpaperDisplay(),b=wallpaperPanelBounds(d),nb=wallpaperNativePosition(d,b);desktopWin.setBounds(b);wallpaperApi.attachToDesktop(desktopWin,nb);wallpaperApi.setClickThrough(desktopWin,true);desktopWin.setIgnoreMouseEvents(true);desktopWin.showInactive();wallpaperApi.sendToBottom(desktopWin);attachTries=0;attachBusy=false;attachTimer=null;isWallpaperAttached=true;console.log('[DexPad] Wallpaper mirror attached.');}catch(err){if(attachTries<ATTACH_MAX){attachTries++;console.warn(`[DexPad] Wallpaper attach ${attachTries}/${ATTACH_MAX} failed: ${err.message}`);attachTimer=setTimeout(doAttach,ATTACH_DELAY);return;}console.error('[DexPad] Wallpaper attach gave up:',err.message);attachTries=0;attachBusy=false;attachTimer=null;isWallpaperAttached=false;store.set('wallpaperMode',false);destroyDesktopWindow();rebuildTray();showControlWindow();}}
function createDesktopWindow(){if(process.platform!=='win32'||!wallpaperApi){store.set('wallpaperMode',false);showControlWindow();return null;}if(desktopWin&&!desktopWin.isDestroyed()){attachWallpaper();return desktopWin;}desktopWin=new BrowserWindow({...wallpaperPanelBounds(),show:false,frame:false,transparent:true,resizable:false,movable:false,focusable:false,skipTaskbar:true,hasShadow:false,backgroundColor:'#00000000',webPreferences:{contextIsolation:true,sandbox:true,preload:PRELOAD}});desktopWin.setMenu(null);desktopWin.setIgnoreMouseEvents(true);desktopWin.loadFile(WORKSPACE_HTML,{search:'mode=wallpaper'}).catch(e=>console.warn('[DexPad] load wallpaper:',e.message));desktopWin.webContents.once('did-finish-load',()=>{attachTimer=setTimeout(attachWallpaper,150);});desktopWin.on('closed',()=>{desktopWin=null;});return desktopWin;}
function destroyDesktopWindow(){if(attachTimer){clearTimeout(attachTimer);attachTimer=null;}attachBusy=false;attachTries=0;isWallpaperAttached=false;if(!desktopWin||desktopWin.isDestroyed())return;try{wallpaperApi?.detachFromDesktop(desktopWin);}catch(e){console.warn('[DexPad] wallpaper detach:',e.message);}desktopWin.destroy();desktopWin=null;}
function refreshWallpaper(){if(!store.get('wallpaperMode')||process.platform!=='win32')return false;if(!desktopWin||desktopWin.isDestroyed())createDesktopWindow();else{publishState();attachWallpaper();}return true;}
function startExplorerWatch(){if(explorerWatchTimer)clearInterval(explorerWatchTimer);explorerWatchTimer=setInterval(()=>{if(quitting||!store.get('wallpaperMode'))return;if(isWallpaperAttached&&!attachBusy&&desktopWin&&!desktopWin.isDestroyed()&&wallpaperApi&&!wallpaperApi.isWindowAttached(desktopWin)){console.warn('[DexPad] Wallpaper mirror attachment lost.');isWallpaperAttached=false;attachWallpaper();}},4000);}
function setWallpaperMode(enabled){store.set('wallpaperMode',Boolean(enabled));if(enabled){createDesktopWindow();}else{destroyDesktopWindow();}publishState();rebuildTray();}
function buildTrayIcon(){for(const p of[path.join(__dirname,'../../assets/icon.png'),path.join(__dirname,'../assets/icon.png'),path.join(__dirname,'../../assets/icon.ico')]){try{const img=nativeImage.createFromPath(p);if(!img.isEmpty())return img;}catch(_){} }return nativeImage.createEmpty();}
function createTray(){if(tray)return;tray=new Tray(buildTrayIcon());tray.setToolTip('DexPad');tray.on('click',showControlWindow);rebuildTray();}
function rebuildTray(){if(!tray)return;const wp=Boolean(store.get('wallpaperMode'));tray.setContextMenu(Menu.buildFromTemplate([{label:'Open DexPad',click:showControlWindow},{label:'Refresh Wallpaper Mirror',click:refreshWallpaper},{type:'separator'},{label:'Wallpaper Mirror',type:'checkbox',checked:wp,click:()=>setWallpaperMode(!wp)},{label:'Settings',click:showSettingsWindow},{type:'separator'},{label:'Quit DexPad',click:quitApp}]));}
function showSettingsWindow(){if(settingsWin&&!settingsWin.isDestroyed()){settingsWin.show();settingsWin.focus();return;}settingsWin=new BrowserWindow({width:520,height:440,resizable:false,minimizable:false,title:'DexPad Settings',backgroundColor:'#090b0e',webPreferences:{contextIsolation:true,sandbox:true,preload:PRELOAD}});settingsWin.setMenuBarVisibility(false);settingsWin.loadFile(path.join(RENDERER,'settings.html'));settingsWin.on('closed',()=>{settingsWin=null;});}
function quitApp(){quitting=true;if(explorerWatchTimer)clearInterval(explorerWatchTimer);if(attachTimer)clearTimeout(attachTimer);globalShortcut.unregisterAll();destroyDesktopWindow();workspaceWin?.destroy();settingsWin?.destroy();tray?.destroy();app.quit();}
ipcMain.handle('dexpad:get-state',()=>currentState());
ipcMain.handle('dexpad:save-workspace',(event,payload)=>saveWorkspace(payload?.cards,payload?.connections,event.sender,payload?.profileId));
ipcMain.on('dexpad:save-workspace-sync',(event,payload)=>{saveWorkspaceSync(payload).then(()=>{event.returnValue=true;}).catch(()=>{event.returnValue=false;});});
ipcMain.handle('dexpad:get-profiles',()=>({profiles:profileSummary(),activeProfileId}));ipcMain.handle('dexpad:switch-profile',(_,id)=>switchProfile(id));ipcMain.handle('dexpad:create-profile',(_,name)=>createProfile(name));ipcMain.handle('dexpad:rename-profile',(_,id,name)=>renameProfile(id,name));
ipcMain.handle('dexpad:set-startup',(_,enabled)=>{if(typeof enabled==='boolean')applyStartup(enabled);publishState();return currentState();});ipcMain.handle('dexpad:set-wallpaper-mode',(_,enabled)=>{if(typeof enabled==='boolean')setWallpaperMode(enabled);return currentState();});ipcMain.handle('dexpad:set-state',(_,state)=>{if(typeof state?.startup==='boolean')applyStartup(state.startup);if(typeof state?.wallpaperMode==='boolean')setWallpaperMode(state.wallpaperMode);return currentState();});ipcMain.handle('dexpad:refresh-wallpaper',()=>refreshWallpaper());ipcMain.handle('dexpad:open-workspace',()=>{showControlWindow();return true;});ipcMain.handle('dexpad:open-url',(_,url)=>{if(!isValidUrl(url))throw new Error('Only http(s) URLs are permitted.');return shell.openExternal(url);});
app.whenReady().then(()=>{applyStartup(Boolean(store.get('startup')));globalShortcut.register('CommandOrControl+Alt+D',showControlWindow);createTray();startExplorerWatch();const hidden=process.argv.includes('--hidden');if(!hidden)showControlWindow();if(store.get('wallpaperMode'))createDesktopWindow();screen.on('display-metrics-changed',()=>refreshWallpaper());screen.on('display-added',()=>refreshWallpaper());screen.on('display-removed',()=>refreshWallpaper());});app.on('second-instance',showControlWindow);app.on('activate',showControlWindow);app.on('window-all-closed',e=>e.preventDefault());app.on('before-quit',()=>{quitting=true;globalShortcut.unregisterAll();});
