'use strict';

const MODE=new URLSearchParams(location.search).get('mode')||'control';
const WALLPAPER=MODE==='wallpaper';
if(WALLPAPER)document.body.classList.add('wallpaper');
const $=id=>document.getElementById(id),canvas=$('canvas'),world=$('world'),connectionsSvg=$('connections'),selectionToolbar=$('selection-toolbar'),emptyState=$('empty-state'),zoomLevel=$('zoom-level');
let cards=[],connections=[],activeFilter='all',saveTimer=null,savePromise=null,drag=null,pan=null,space=false,history=[],future=[],camera={x:0,y:0,zoom:1};
const selected=new Set(),clone=v=>JSON.parse(JSON.stringify(v)),uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
function snap(){return{cards:clone(cards),connections:clone(connections)}}
function remember(){if(WALLPAPER)return;history.push(snap());if(history.length>100)history.shift();future=[];updateHistory()}
function updateHistory(){if($('btn-undo'))$('btn-undo').disabled=WALLPAPER||!history.length;if($('btn-redo'))$('btn-redo').disabled=WALLPAPER||!future.length}
function restore(s){cards=clone(s.cards||[]);connections=clone(s.connections||[]);selected.clear();render();flushSave()}
function undo(){if(WALLPAPER||!history.length)return;future.push(snap());restore(history.pop())}
function redo(){if(WALLPAPER||!future.length)return;history.push(snap());restore(future.pop())}
function activeId(){return window.DexProfiles?.getActiveId?.()||null}
function saveNow(){if(WALLPAPER)return Promise.resolve();clearTimeout(saveTimer);saveTimer=null;if(savePromise)return savePromise;const payload={cards:clone(cards),connections:clone(connections),profileId:activeId()};savePromise=window.dexpad.saveWorkspace(payload).finally(()=>{savePromise=null});return savePromise}
function scheduleSave(){if(WALLPAPER)return;clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveNow(),350)}
window.flushSave=saveNow;
function match(c){if(activeFilter==='favorite')return !!c.pinned;if(activeFilter!=='all'&&activeFilter!=='other')return c.type===activeFilter;if(activeFilter==='other')return !['note','todo','link'].includes(c.type);return true}
function setCounts(){const count={all:cards.length,note:0,todo:0,link:0,favorite:0};cards.forEach(c=>{if(count[c.type]!=null)count[c.type]++;if(c.pinned)count.favorite++});Object.entries(count).forEach(([k,v])=>{const e=$('count-'+k);if(e)e.textContent=v})}
function position(el,c){el.style.left=c.x+'px';el.style.top=c.y+'px';el.style.width=c.width+'px';el.style.height=c.height+'px';el.style.zIndex=c.zIndex||1}
function htmlEsc(s){return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
function buildCard(c){
  const el=document.createElement('article');el.className='card';el.dataset.id=c.id;el.dataset.type=c.type;el.dataset.color=c.color||'default';el.dataset.pinned=String(!!c.pinned);el.dataset.locked=String(!!c.locked);position(el,c);
  const head=document.createElement('div');head.className='card-head';
  const type=document.createElement('span');type.className='card-type';type.textContent=c.type;
  const actions=document.createElement('div');actions.className='card-actions';
  const pin=document.createElement('button');pin.className='card-action';pin.textContent=c.pinned?'★':'☆';pin.title='Pin';pin.disabled=WALLPAPER;pin.onclick=e=>{e.stopPropagation();remember();c.pinned=!c.pinned;render();scheduleSave()};
  const del=document.createElement('button');del.className='card-action';del.textContent='×';del.title='Delete';del.disabled=WALLPAPER;del.onclick=e=>{e.stopPropagation();remember();deleteByIds(new Set([c.id]));};
  actions.append(pin,del);head.append(type,actions);head.addEventListener('mousedown',e=>startDrag(e,c));
  el.appendChild(head);
  const body=document.createElement('div');body.className='card-body';
  const ctx={card:c,wallpaper:WALLPAPER,disabled:WALLPAPER,patch:p=>patch(c.id,p),flush:saveNow,openUrl:u=>window.dexpad.openUrl(u),openBoard:()=>{},isValidUrl:u=>/^https?:\/\//i.test(u||''),validateImageSource:u=>/^(https?:\/\/|data:image\/)/i.test(u||'')};
  const renderer=window.DexBlockRegistry?.get?.(c.type);if(typeof renderer==='function'){try{renderer(body,ctx)}catch(err){const pre=document.createElement('pre');pre.textContent='Block render error: '+(err.message||err);body.append(pre);console.error(err)}}else{const title=document.createElement('input');title.className='block-input';title.value=c.title||'';title.disabled=WALLPAPER;title.oninput=()=>patch(c.id,{title:title.value});body.append(title)}
  el.appendChild(body);el.addEventListener('mousedown',e=>{if(e.target.closest('input,textarea,button'))return;toggle(c.id,e.shiftKey)});return el;
}
function toggle(id,multi){if(WALLPAPER)return;if(!multi)selected.clear();selected.has(id)&&multi?selected.delete(id):selected.add(id);updateSelection()}
function updateSelection(){world.querySelectorAll('.card').forEach(e=>e.classList.toggle('card--selected',selected.has(e.dataset.id)));if(selectionToolbar)selectionToolbar.hidden=WALLPAPER||!selected.size;if($('selection-count'))$('selection-count').textContent=`${selected.size} selected`}
function patch(id,p){if(WALLPAPER)return;const c=cards.find(x=>x.id===id);if(!c||c.locked)return;Object.assign(c,p);scheduleSave();const el=world.querySelector(`[data-id="${CSS.escape(id)}"]`);if(el&&p.title!==undefined){const inp=el.querySelector('[data-field="title"]');if(inp&&inp.value!==p.title)inp.value=p.title}setCounts()}
function deleteByIds(ids){if(WALLPAPER)return;cards=cards.filter(c=>!ids.has(c.id));connections=connections.filter(x=>!ids.has(x.a)&&!ids.has(x.b));selected.clear();render();scheduleSave()}
function addCard(type){if(WALLPAPER)return;remember();const i=cards.length;const c={id:uid('block'),type,title:type[0].toUpperCase()+type.slice(1),body:'',url:'',done:false,markdown:'',src:'',path:'',description:'',children:[],tags:[],pinned:false,locked:false,collapsed:false,parentId:null,color:['default','blue','green','amber','rose','purple'][i%6],x:80+(i%3)*330-camera.x,y:80+(Math.floor(i/3)%3)*230-camera.y,width:type==='todo'?300:320,height:type==='note'||type==='markdown'?210:180,zIndex:i+1};cards.push(c);selected.clear();selected.add(c.id);render();scheduleSave();}
function render(){world.replaceChildren();cards.filter(match).forEach(c=>world.appendChild(buildCard(c)));setCounts();updateSelection();emptyState.hidden=cards.length>0;applyCamera();}
function drawConnections(){connectionsSvg.replaceChildren();const map=new Map(cards.map(c=>[c.id,c]));connections.forEach(x=>{const a=map.get(x.a),b=map.get(x.b);if(!a||!b||!match(a)||!match(b))return;const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',(a.x+a.width/2)*camera.zoom+camera.x);line.setAttribute('y1',(a.y+a.height/2)*camera.zoom+camera.y);line.setAttribute('x2',(b.x+b.width/2)*camera.zoom+camera.x);line.setAttribute('y2',(b.y+b.height/2)*camera.zoom+camera.y);line.setAttribute('stroke','rgba(140,182,255,.42)');line.setAttribute('stroke-width','2');line.setAttribute('stroke-linecap','round');connectionsSvg.appendChild(line)})}
function applyCamera(){if(!world)return;world.style.transform=`translate(${camera.x}px,${camera.y}px) scale(${camera.zoom})`;const grid=$('.canvas-grid');if(grid){grid.style.transform=`translate(${camera.x%28}px,${camera.y%28}px) scale(${camera.zoom})`;grid.style.backgroundSize=`${28/camera.zoom}px ${28/camera.zoom}px`}if(zoomLevel)zoomLevel.textContent=Math.round(camera.zoom*100)+'%';drawConnections()}
function zoomAt(value,x=canvas.clientWidth/2,y=canvas.clientHeight/2){const z=Math.max(.3,Math.min(2.5,value));const ratio=z/camera.zoom;camera.x=x-(x-camera.x)*ratio;camera.y=y-(y-camera.y)*ratio;camera.zoom=z;applyCamera()}
function startDrag(e,c){if(WALLPAPER||c.locked||e.button!==0)return;e.preventDefault();if(!selected.has(c.id))toggle(c.id,e.shiftKey);if(!selected.has(c.id))selected.add(c.id);drag={sx:e.clientX,sy:e.clientY,items:[...selected].map(id=>{const x=cards.find(v=>v.id===id);return{id,x:x.x,y:x.y}})};remember();window.addEventListener('mousemove',moveDrag);window.addEventListener('mouseup',endDrag,{once:true})}
function moveDrag(e){if(!drag)return;const dx=(e.clientX-drag.sx)/camera.zoom,dy=(e.clientY-drag.sy)/camera.zoom;drag.items.forEach(i=>{const c=cards.find(x=>x.id===i.id);if(!c)return;c.x=Math.round(i.x+dx);c.y=Math.round(i.y+dy);const el=world.querySelector(`[data-id="${CSS.escape(c.id)}"]`);if(el)position(el,c)});drawConnections()}
function endDrag(){if(!drag)return;drag=null;window.removeEventListener('mousemove',moveDrag);scheduleSave()}
function connectSelected(){if(WALLPAPER||selected.size!==2){toast('Select exactly two blocks');return}remember();const [a,b]=[...selected];if(!connections.some(x=>(x.a===a&&x.b===b)||(x.a===b&&x.b===a)))connections.push({id:uid('connection'),a,b,label:''});render();scheduleSave()}
function groupSelected(){if(WALLPAPER||selected.size<2){toast('Select two or more blocks');return}remember();const ids=[...selected];const g={id:uid('block'),type:'group',title:'Group',body:'',children:ids,x:Math.min(...cards.filter(c=>selected.has(c.id)).map(c=>c.x))-20,y:Math.min(...cards.filter(c=>selected.has(c.id)).map(c=>c.y))-45,width:420,height:240,zIndex:Math.max(...cards.map(c=>c.zIndex||1))+1,color:'purple',pinned:false,locked:false,tags:[],done:false,markdown:'',src:'',path:'',url:'',description:'',parentId:null,collapsed:false};cards.push(g);selected.clear();selected.add(g.id);render();scheduleSave()}
function togglePin(){if(WALLPAPER||!selected.size)return;remember();cards.forEach(c=>{if(selected.has(c.id))c.pinned=!c.pinned});render();scheduleSave()}
function search(q){const root=$('search-results');if(!root)return;root.replaceChildren();q=q.trim().toLowerCase();cards.filter(c=>!q||[c.title,c.body,c.markdown,c.url,c.path,c.type].some(v=>String(v||'').toLowerCase().includes(q))).slice(0,60).forEach(c=>{const row=document.createElement('div');row.className='result-row';row.innerHTML=`<div><strong>${htmlEsc(c.title||c.type)}</strong><small>${htmlEsc(c.body||c.markdown||c.url||c.path||'')}</small></div><span class="result-type">${htmlEsc(c.type)}</span>`;row.onclick=()=>{camera.x=Math.round(canvas.clientWidth/2-(c.x+c.width/2)*camera.zoom);camera.y=Math.round(canvas.clientHeight/2-(c.y+c.height/2)*camera.zoom);selected.clear();selected.add(c.id);close('search-overlay');render()};root.appendChild(row)})}
const commands=[['Add note','note'],['Add task','todo'],['Add link','link'],['Add markdown','markdown'],['Add image','image'],['Add file','file'],['Add column','column'],['Add group','group'],['Add board','board'],['Group selected','group'],['Pin selected','pin'],['Connect selected','connect'],['Undo','undo'],['Redo','redo'],['Export','export'],['Import','import']];
function runCommand(c){close('command-overlay');if(c==='undo')return undo();if(c==='redo')return redo();if(c==='group')return groupSelected();if(c==='pin')return togglePin();if(c==='connect')return connectSelected();if(c==='export')return exportWorkspace();if(c==='import')return $('import-input')?.click();addCard(c)}
function open(id){const e=$(id);if(e){e.hidden=false;e.querySelector('input')?.focus()}}
function close(id){const e=$(id);if(e)e.hidden=true}
function exportWorkspace(){const blob=new Blob([JSON.stringify({schemaVersion:5,profileId:activeId(),cards,connections},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='dexpad-workspace.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importWorkspace(file){if(!file||WALLPAPER)return;const r=new FileReader();r.onload=async()=>{try{const d=JSON.parse(String(r.result));if(!Array.isArray(d.cards)||d.cards.length>5000)throw Error('Invalid workspace');remember();const saved=await window.dexpad.saveWorkspace({cards:d.cards,connections:Array.isArray(d.connections)?d.connections:[],profileId:activeId()});cards=saved.cards||[];connections=saved.connections||[];render();toast('Imported')}catch(e){console.error(e);toast('Import failed')}};r.readAsText(file)}
function toast(msg){let e=$('toast');if(!e){e=document.createElement('div');e.id='toast';e.className='toast';document.body.appendChild(e)}e.textContent=msg;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1300)}
$('btn-add')?.addEventListener('click',e=>{$('add-menu').hidden=!$('add-menu').hidden;e.stopPropagation()});document.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>{addCard(b.dataset.add);$('add-menu').hidden=true}));
$('btn-undo')?.addEventListener('click',undo);$('btn-redo')?.addEventListener('click',redo);$('btn-save')?.addEventListener('click',saveNow);$('btn-search')?.addEventListener('click',()=>open('search-overlay'));$('btn-command')?.addEventListener('click',()=>{renderCommands();open('command-overlay')});$('btn-delete-selected')?.addEventListener('click',()=>deleteByIds(new Set(selected)));$('btn-templates')?.addEventListener('click',()=>{remember();addCard('note');});$('btn-export')?.addEventListener('click',exportWorkspace);$('btn-import')?.addEventListener('click',()=>$('import-input')?.click());$('import-input')?.addEventListener('change',e=>{importWorkspace(e.target.files?.[0]);e.target.value=''});$('btn-zoom-in')?.addEventListener('click',()=>zoomAt(camera.zoom+.15));$('btn-zoom-out')?.addEventListener('click',()=>zoomAt(camera.zoom-.15));$('btn-zoom-reset')?.addEventListener('click',()=>{camera={x:0,y:0,zoom:1};applyCamera()});$('search-input')?.addEventListener('input',e=>search(e.target.value));document.querySelectorAll('.rail-item[data-filter]').forEach(b=>b.addEventListener('click',()=>{activeFilter=b.dataset.filter;document.querySelectorAll('.rail-item[data-filter]').forEach(x=>x.classList.toggle('active',x===b));render()}));document.querySelectorAll('[data-close-overlay]').forEach(b=>b.addEventListener('click',()=>close(b.dataset.closeOverlay)));
function renderCommands(){const root=$('command-results');if(!root)return;root.replaceChildren();commands.forEach(([label,cmd])=>{const row=document.createElement('div');row.className='result-row';row.innerHTML=`<div><strong>${htmlEsc(label)}</strong></div>`;row.onclick=()=>runCommand(cmd);root.appendChild(row)})}
canvas?.addEventListener('mousedown',e=>{if(e.target===canvas){selected.clear();updateSelection()}if(e.button===1||(space&&e.button===0)){e.preventDefault();pan={sx:e.clientX,sy:e.clientY,x:camera.x,y:camera.y};canvas.classList.add('is-panning');window.addEventListener('mousemove',movePan);window.addEventListener('mouseup',endPan,{once:true})}});
function movePan(e){if(!pan)return;camera.x=pan.x+(e.clientX-pan.sx);camera.y=pan.y+(e.clientY-pan.sy);applyCamera()}function endPan(){pan=null;canvas.classList.remove('is-panning');window.removeEventListener('mousemove',movePan)}
canvas?.addEventListener('wheel',e=>{if(WALLPAPER)return;e.preventDefault();const r=canvas.getBoundingClientRect();zoomAt(camera.zoom*(e.deltaY<0?1.08:.92),e.clientX-r.left,e.clientY-r.top)},{passive:false});
document.addEventListener('keydown',e=>{const editing=/INPUT|TEXTAREA|SELECT/.test(e.target?.tagName||'');if(e.key==='Escape'){close('search-overlay');close('command-overlay');if($('add-menu'))$('add-menu').hidden=true}if(!editing&&e.key===' ') {space=true;e.preventDefault()}if(!editing&&(e.key==='Delete'||e.key==='Backspace'))deleteByIds(new Set(selected));if(!editing&&(e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}if(!editing&&(e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='f'){e.preventDefault();open('search-overlay')}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();renderCommands();open('command-overlay')}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'&&!WALLPAPER){e.preventDefault();saveNow()} });document.addEventListener('keyup',e=>{if(e.key===' ')space=false});document.addEventListener('click',e=>{if($('add-menu')&&!$('add-menu').hidden&&!e.target.closest('#btn-add')&&!e.target.closest('#add-menu'))$('add-menu').hidden=true});
window.addEventListener('resize',drawConnections);
window.dexpad.onStateUpdated(state=>{if(!state)return;cards=Array.isArray(state.cards)?state.cards:[];connections=Array.isArray(state.connections)?state.connections:[];if(!WALLPAPER)render()});
window.dexpad.getState().then(state=>{cards=Array.isArray(state?.cards)?state.cards:[];connections=Array.isArray(state?.connections)?state.connections:[];render();}).catch(e=>{console.error(e);toast('Unable to load workspace')});
