'use strict';

const MODE = new URLSearchParams(window.location.search).get('mode') || 'control';
const WALLPAPER = MODE === 'wallpaper';
if (WALLPAPER) document.body.classList.add('wallpaper');

const $ = (id) => document.getElementById(id);
const canvas = $('canvas'), world = $('world'), connectionsSvg = $('connections');
const emptyState = $('empty-state'), selectionToolbar = $('selection-toolbar');
const zoomLevel = $('zoom-level');
let cards = [], activeFilter = 'all', searchQuery = '', saveTimer = null;
let isSaving = false, savePending = false, dragging = null, pan = null;
let spaceDown = false, history = [], future = [], historyStamp = 0;
let connections = JSON.parse(localStorage.getItem('dexpad-connections') || '[]');
const selectedIds = new Set();
const uid = () => `block-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;
const clone = (v) => JSON.parse(JSON.stringify(v));

const camera = { x: 0, y: 0, zoom: 1 };
function applyCamera() { if (WALLPAPER) return; world.style.transform=`translate(${camera.x}px,${camera.y}px) scale(${camera.zoom})`;canvas.style.backgroundPosition=`${camera.x}px ${camera.y}px`;canvas.style.backgroundSize=`${28*camera.zoom}px ${28*camera.zoom}px`;zoomLevel.textContent=`${Math.round(camera.zoom*100)}%`;drawConnections(); }
function setZoom(z,ax=canvas.clientWidth/2,ay=canvas.clientHeight/2){const next=Math.max(.3,Math.min(2.5,z)),ratio=next/camera.zoom;camera.x=ax-(ax-camera.x)*ratio;camera.y=ay-(ay-camera.y)*ratio;camera.zoom=next;applyCamera()}
function resetCamera(){camera.x=0;camera.y=0;camera.zoom=1;applyCamera()}
function recordHistory(force=false){const now=Date.now();if(!force&&now-historyStamp<700)return;history.push(clone(cards));if(history.length>80)history.shift();future=[];historyStamp=now;updateHistoryButtons()}
function restoreSnapshot(snapshot){cards=clone(snapshot||[]);selectedIds.clear();reconcile();scheduleSave()}
function undo(){if(!history.length||WALLPAPER)return;future.push(clone(cards));restoreSnapshot(history.pop())}
function redo(){if(!future.length||WALLPAPER)return;history.push(clone(cards));restoreSnapshot(future.pop())}
function updateHistoryButtons(){$('btn-undo').disabled=!history.length;$('btn-redo').disabled=!future.length}
function maxZ(){return cards.reduce((m,c)=>Math.max(m,Number(c.zIndex)||1),1)}
function patchCard(id,patch){const card=cards.find(c=>c.id===id);if(!card||WALLPAPER||card.locked)return;recordHistory();Object.assign(card,patch);scheduleSave();reconcileCard(id)}
function scheduleSave(){if(WALLPAPER)return;clearTimeout(saveTimer);saveTimer=setTimeout(flushSave,300)}
async function flushSave(){if(WALLPAPER)return;clearTimeout(saveTimer);saveTimer=null;if(isSaving){savePending=true;return}isSaving=true;try{await window.dexpad.saveCards(cards);setSaveStatus('Saved')}catch(err){console.error('[DexPad] Save failed',err);setSaveStatus('Save failed')}finally{isSaving=false;if(savePending){savePending=false;flushSave()}}}
function setSaveStatus(label){const b=$('btn-save');if(!b)return;b.textContent=label==='Saved'?'Saved ✓':label;clearTimeout(b._timer);b._timer=setTimeout(()=>b.textContent='Save',900)}
function makeCard(type){const col=cards.length%3,row=Math.floor(cards.length/3);return{id:uid(),type,color:'default',pinned:false,locked:false,collapsed:false,tags:[],title:type==='todo'?'New task':type==='link'?'New link':type==='markdown'?'New markdown':type==='image'?'New image':type==='file'?'New file':type==='column'?'New column':type==='group'?'New group':type==='board'?'New board':'New note',body:'',url:type==='link'?'https://':'',markdown:'',src:'',path:'',description:'',done:false,children:[],x:60+col*340,y:60+row*230,width:type==='column'?280:300,height:type==='note'||type==='markdown'?210:170,zIndex:maxZ()+1}}
function addCard(type,at=null){if(WALLPAPER)return;recordHistory(true);const c=makeCard(type);if(at){c.x=Math.max(20,Math.round((at.x-camera.x)/camera.zoom));c.y=Math.max(20,Math.round((at.y-camera.y)/camera.zoom))}cards.push(c);selectedIds.clear();selectedIds.add(c.id);reconcile();flushSave();closeMenus()}
function deleteIds(ids){if(!ids.size||WALLPAPER)return;recordHistory(true);cards=cards.filter(c=>!ids.has(c.id));for(const id of ids)selectedIds.delete(id);reconcile();flushSave()}
function togglePin(ids){if(WALLPAPER)return;recordHistory(true);for(const c of cards)if(ids.has(c.id))c.pinned=!c.pinned;reconcile();flushSave()}
function groupSelected(){if(WALLPAPER||selectedIds.size<2)return toast('Select at least two blocks');recordHistory(true);const items=cards.filter(c=>selectedIds.has(c.id));const x=Math.max(20,Math.min(...items.map(c=>c.x))-24),y=Math.max(20,Math.min(...items.map(c=>c.y))-46);const r=Math.max(...items.map(c=>c.x+c.width))-x+24,h=Math.max(...items.map(c=>c.y+c.height))-y+60;const g=makeCard('group');g.title='Group';g.x=x;g.y=y;g.width=Math.max(280,r);g.height=Math.max(180,h);g.children=items.map(c=>c.id);g.zIndex=Math.max(1,Math.min(...items.map(c=>Number(c.zIndex)||1))-1);cards.push(g);selectedIds.clear();selectedIds.add(g.id);reconcile();flushSave()}
function connectSelected(){if(WALLPAPER||selectedIds.size!==2)return toast('Select exactly two blocks');const[a,b]=[...selectedIds];if(!connections.some(c=>c.a===a&&c.b===b||c.a===b&&c.b===a))connections.push({id:uid(),a,b});localStorage.setItem('dexpad-connections',JSON.stringify(connections));drawConnections();toast('Connected')}
function openBoard(){toast('Nested board navigation is queued; the board block is available.')}
function isValidUrl(v){try{const u=new URL(v);return u.protocol==='http:'||u.protocol==='https:'}catch(_){return false}}
function openUrl(v){if(isValidUrl(v))window.dexpad.openUrl(v).catch(console.error)}
function closeMenus(){$('add-menu').hidden=true;$('templates-menu')?.remove()}
function toast(message){let t=$('toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.appendChild(t)}t.textContent=message;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),1400)}
function buildCard(card){const el=document.createElement('article');el.className='card';el.dataset.id=card.id;el.dataset.type=card.type;el.dataset.color=card.color||'default';el.dataset.pinned=String(!!card.pinned);positionCard(el,card);if(selectedIds.has(card.id))el.classList.add('card--selected');const head=document.createElement('div');head.className='card-head';const type=document.createElement('span');type.className='card-type';type.textContent=card.type;head.appendChild(type);if(!WALLPAPER){const actions=document.createElement('div');actions.className='card-actions';for(const[txt,title,fn]of[['☆',card.pinned?'Unpin':'Pin',()=>{recordHistory(true);card.pinned=!card.pinned;reconcile();flushSave()}],['↗','Bring to front',()=>{recordHistory(true);card.zIndex=maxZ()+1;reconcile();flushSave()}],['×','Delete',()=>deleteIds(new Set([card.id]))]]){const b=document.createElement('button');b.className='card-action'+(txt==='×'?' danger':'');b.textContent=txt;b.title=title;b.addEventListener('click',e=>{e.stopPropagation();fn()});actions.appendChild(b)}head.appendChild(actions);head.addEventListener('mousedown',e=>startDrag(e,card,el))}el.appendChild(head);const body=document.createElement('div');body.className='card-body';const renderer=window.DexBlockRegistry?.get(card.type);if(renderer)renderer(body,{card,wallpaper:WALLPAPER,patch:p=>patchCard(card.id,p),flush:flushSave,isValidUrl,openUrl,openBoard});const meta=document.createElement('div');meta.className='block-meta';for(const t of card.tags||[]){const s=document.createElement('span');s.textContent=`#${t}`;meta.appendChild(s)}if(card.pinned){const s=document.createElement('span');s.textContent='★';meta.appendChild(s)}if(meta.children.length)body.appendChild(meta);el.appendChild(body);observeResize(el,card);el.addEventListener('mousedown',e=>{if(WALLPAPER)return;if(!e.target.closest('button,input,textarea')){if(e.shiftKey){selectedIds.has(card.id)?selectedIds.delete(card.id):selectedIds.add(card.id)}else if(!selectedIds.has(card.id)){selectedIds.clear();selectedIds.add(card.id)}updateSelection()}});return el}
function positionCard(el,c){el.style.left=`${c.x}px`;el.style.top=`${c.y}px`;el.style.width=`${c.width}px`;el.style.height=`${c.height}px`;el.style.zIndex=String(c.zIndex||1);el.dataset.color=c.color||'default';el.dataset.pinned=String(!!c.pinned)}
function reconcileCard(id){const c=cards.find(x=>x.id===id),el=world.querySelector(`[data-id="${CSS.escape(id)}"]`);if(!c||!el){reconcile();return}positionCard(el,c);syncInputs(el,c);drawConnections()}
function syncInputs(el,c){for(const x of el.querySelectorAll('[data-field]')){if(x===document.activeElement)continue;const v=String(c[x.dataset.field]??'');if(x.type==='checkbox')x.checked=!!c[x.dataset.field];else if(x.value!==v)x.value=v}}
function matches(c){const q=searchQuery.trim().toLowerCase();const filter=activeFilter;if(filter!=='all'&&filter!=='favorite'&&c.type!==filter)return false;if(filter==='favorite'&&!c.pinned)return false;if(!q)return true;return[c.title,c.body,c.url,c.markdown,c.path,...(c.tags||[])].some(v=>String(v||'').toLowerCase().includes(q))}
function reconcile(){disconnectAllObservers();world.replaceChildren(...cards.filter(matches).map(buildCard));updateSelection();updateCounts();emptyState.hidden=WALLPAPER||cards.length>0;drawConnections()}
const ros=new Map();function disconnectAllObservers(){for(const ro of ros.values())ro.disconnect();ros.clear()}function observeResize(el,c){if(WALLPAPER||typeof ResizeObserver==='undefined')return;const ro=new ResizeObserver(([e])=>{const w=Math.max(220,Math.min(900,Math.round(e.contentRect.width))),h=Math.max(140,Math.min(900,Math.round(e.contentRect.height)));if(c.width!==w||c.height!==h){recordHistory();c.width=w;c.height=h;scheduleSave()}});ro.observe(el);ros.set(c.id,ro)}
function updateSelection(){for(const el of world.querySelectorAll('.card'))el.classList.toggle('card--selected',selectedIds.has(el.dataset.id));selectionToolbar.hidden=WALLPAPER||!selectedIds.size;$('selection-count').textContent=`${selectedIds.size} selected`}
function updateCounts(){const all=cards.length;$('count-all').textContent=all;$('count-note').textContent=cards.filter(c=>c.type==='note').length;$('count-todo').textContent=cards.filter(c=>c.type==='todo').length;$('count-link').textContent=cards.filter(c=>c.type==='link').length;$('count-favorite').textContent=cards.filter(c=>c.pinned).length;updateHistoryButtons()}
function startDrag(e,c){if(WALLPAPER||c.locked)return;e.preventDefault();if(!selectedIds.has(c.id)){selectedIds.clear();selectedIds.add(c.id);updateSelection()}recordHistory(true);dragging={startX:e.clientX,startY:e.clientY,multi:[...selectedIds].map(id=>{const x=cards.find(q=>q.id===id);return x?{c:x,x:x.x,y:x.y}:null}).filter(Boolean)};document.addEventListener('mousemove',onDrag);document.addEventListener('mouseup',endDrag,{once:true})}
function onDrag(e){if(!dragging)return;const dx=(e.clientX-dragging.startX)/camera.zoom,dy=(e.clientY-dragging.startY)/camera.zoom;for(const item of dragging.multi)if(!item.c.locked){item.c.x=Math.max(0,Math.round(item.x+dx));item.c.y=Math.max(0,Math.round(item.y+dy))}reconcile()}
function endDrag(){if(!dragging)return;dragging=null;document.removeEventListener('mousemove',onDrag);flushSave()}
function startPan(e){if(WALLPAPER)return;if(e.button!==1&&!spaceDown)return;e.preventDefault();pan={x:e.clientX,y:e.clientY,cx:camera.x,cy:camera.y};document.addEventListener('mousemove',onPan);document.addEventListener('mouseup',endPan,{once:true});canvas.classList.add('is-panning')}
function onPan(e){if(!pan)return;camera.x=pan.cx+(e.clientX-pan.x);camera.y=pan.cy+(e.clientY-pan.y);applyCamera()}
function endPan(){pan=null;canvas.classList.remove('is-panning');document.removeEventListener('mousemove',onPan)}
function drawConnections(){if(!connectionsSvg)return;connectionsSvg.replaceChildren();if(WALLPAPER)return;for(const cn of connections){const a=cards.find(c=>c.id===cn.a),b=cards.find(c=>c.id===cn.b);if(!a||!b)continue;const ax=(a.x+a.width/2)*camera.zoom+camera.x,ay=(a.y+a.height/2)*camera.zoom+camera.y,bx=(b.x+b.width/2)*camera.zoom+camera.x,by=(b.y+b.height/2)*camera.zoom+camera.y;const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',ax);line.setAttribute('y1',ay);line.setAttribute('x2',bx);line.setAttribute('y2',by);line.setAttribute('stroke','rgba(118,168,255,.45)');line.setAttribute('stroke-width','2');line.setAttribute('stroke-linecap','round');connectionsSvg.appendChild(line)}}
function openOverlay(id){$(id).hidden=false;$(id).querySelector('input').focus()}function closeOverlay(id){$(id).hidden=true}
function renderSearch(){const root=$('search-results'),q=$('search-input').value.trim().toLowerCase();root.replaceChildren();if(q!==searchQuery){searchQuery=q;reconcile()}cards.filter(matches).slice(0,30).forEach(c=>{const row=document.createElement('div');row.className='result-row';const left=document.createElement('div');const strong=document.createElement('strong');strong.textContent=c.title||c.type;const small=document.createElement('small');small.textContent=(c.body||c.markdown||c.url||'').slice(0,90);left.append(strong,small);const typ=document.createElement('span');typ.className='result-type';typ.textContent=c.type;row.append(left,typ);row.onclick=()=>{selectedIds.clear();selectedIds.add(c.id);closeOverlay('search-overlay');camera.x=Math.round(canvas.clientWidth/2-c.x-camera.zoom*c.width/2);camera.y=Math.round(canvas.clientHeight/2-c.y-camera.zoom*c.height/2);searchQuery='';activeFilter='all';reconcile()};root.appendChild(row)})}
const commands=[['Add note','Create a note','note'],['Add task','Create a task','todo'],['Add link','Create a link','link'],['Add markdown','Create Markdown','markdown'],['Add image','Create image block','image'],['Add file','Create file block','file'],['Add column','Create a column','column'],['Add group','Create group','group'],['Add board','Create nested board','board'],['Group selected','Group the current selection','group-selected'],['Pin selected','Toggle pin on selection','pin'],['Connect selected','Connect exactly two blocks','connect'],['Export workspace','Export JSON','export'],['Import workspace','Import JSON','import'],['Undo','Undo last edit','undo'],['Redo','Redo last edit','redo'],['Reset view','Reset canvas','reset']];
function renderCommands(){const root=$('command-results'),q=$('command-input').value.trim().toLowerCase();root.replaceChildren();commands.filter(c=>!q||c[0].toLowerCase().includes(q)).slice(0,18).forEach(c=>{const row=document.createElement('div');row.className='result-row';const left=document.createElement('div');const strong=document.createElement('strong');strong.textContent=c[0];const small=document.createElement('small');small.textContent=c[1];left.append(strong,small);row.appendChild(left);row.onclick=()=>runCommand(c[2]);root.appendChild(row)})}
function runCommand(cmd){closeOverlay('command-overlay');if(cmd==='undo')return undo();if(cmd==='redo')return redo();if(cmd==='reset')return resetCamera();if(cmd==='export')return exportWorkspace();if(cmd==='import')return $('import-input').click();if(cmd==='group-selected')return groupSelected();if(cmd==='pin')return togglePin(selectedIds);if(cmd==='connect')return connectSelected();addCard(cmd)}
function exportWorkspace(){const data=JSON.stringify({schemaVersion:3,cards,connections},null,2),blob=new Blob([data],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`dexpad-workspace-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('Workspace exported')}
function importWorkspace(file){const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(!Array.isArray(data.cards))throw new Error('Invalid workspace');recordHistory(true);cards=data.cards;connections=Array.isArray(data.connections)?data.connections:[];localStorage.setItem('dexpad-connections',JSON.stringify(connections));selectedIds.clear();reconcile();flushSave();toast('Workspace imported')}catch(e){console.error(e);toast('Import failed')}};r.readAsText(file)}
function applyTemplate(name){recordHistory(true);if(name==='project'){cards=[];for(const[type,title]of[['column','Ideas'],['column','In progress'],['column','Done'],['note','Project brief'],['todo','First task'],['link','Reference']]){const c=makeCard(type);c.title=title;c.x=70+(cards.length%3)*320;c.y=70+Math.floor(cards.length/3)*210;cards.push(c)}}if(name==='weekly'){cards=[];for(const d of['Monday','Tuesday','Wednesday','Thursday','Friday']){const c=makeCard('todo');c.title=d;c.x=80+(cards.length%3)*330;c.y=80+Math.floor(cards.length/3)*200;cards.push(c)}}selectedIds.clear();reconcile();flushSave();toast('Template applied')}
function templates(){const old=$('templates-menu');if(old){old.remove();return}const m=document.createElement('div');m.id='templates-menu';m.className='floating-menu';m.innerHTML='<button data-template="project">Project board</button><button data-template="weekly">Weekly planner</button>';$('btn-templates').parentElement.style.position='relative';$('btn-templates').parentElement.appendChild(m);m.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>{applyTemplate(b.dataset.template);m.remove()})}
$('btn-add').onclick=()=>{$('add-menu').hidden=!$('add-menu').hidden};document.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>addCard(b.dataset.add)));$('btn-templates').onclick=templates;$('btn-save').onclick=flushSave;$('btn-undo').onclick=undo;$('btn-redo').onclick=redo;$('btn-search').onclick=()=>openOverlay('search-overlay');$('btn-command').onclick=()=>openOverlay('command-overlay');$('btn-delete-selected').onclick=()=>deleteIds(new Set(selectedIds));$('btn-group-selected').onclick=groupSelected;$('btn-pin-selected').onclick=()=>togglePin(selectedIds);$('btn-connect').onclick=connectSelected;$('btn-export').onclick=exportWorkspace;$('btn-import').onclick=()=>$('import-input').click();$('import-input').onchange=e=>{if(e.target.files[0])importWorkspace(e.target.files[0]);e.target.value=''};$('btn-zoom-in').onclick=()=>setZoom(camera.zoom+.15);$('btn-zoom-out').onclick=()=>setZoom(camera.zoom-.15);$('btn-zoom-reset').onclick=resetCamera;document.querySelectorAll('.side-item').forEach(b=>b.onclick=()=>{document.querySelectorAll('.side-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;searchQuery='';reconcile()});$('search-input').oninput=renderSearch;$('command-input').oninput=renderCommands;$('search-overlay').onclick=e=>{if(e.target===$('search-overlay'))closeOverlay('search-overlay')};$('command-overlay').onclick=e=>{if(e.target===$('command-overlay'))closeOverlay('command-overlay')};canvas.addEventListener('mousedown',e=>{if(e.target===canvas)clearSelection();if(e.button===1||spaceDown)startPan(e)});canvas.addEventListener('wheel',e=>{if(WALLPAPER)return;e.preventDefault();const r=canvas.getBoundingClientRect();setZoom(camera.zoom*(e.deltaY<0?1.08:.92),e.clientX-r.left,e.clientY-r.top)},{passive:false});document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.target.matches('input,textarea')){spaceDown=true;e.preventDefault()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='f'){e.preventDefault();openOverlay('search-overlay')}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openOverlay('command-overlay')}if(e.key==='Escape'){closeOverlay('search-overlay');closeOverlay('command-overlay');$('add-menu').hidden=true}if((e.key==='Delete'||e.key==='Backspace')&&!e.target.matches('input,textarea')&&!WALLPAPER)deleteIds(new Set(selectedIds))});document.addEventListener('keyup',e=>{if(e.code==='Space')spaceDown=false});
async function init(){try{const state=await window.dexpad.getState();cards=Array.isArray(state.cards)?state.cards:[];reconcile()}catch(err){console.error('[DexPad] init failed',err)}updateHistoryButtons();applyCamera()}window.addEventListener('resize',drawConnections);init();
